pipeline {
    // These are pre-build sections
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    
    // This is build section
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
                      
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Parellel Trigger'){
            parallel {
                stage('Bastion'){
                    steps {
                        script {
                            build job: '20-bastion',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('SG Rules'){
                    steps {
                        script {
                            build job: '30-sg-rules',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ECR'){
                    steps {
                        script {
                            build job: '40-ecr',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ACM'){
                    steps {
                        script {
                            build job: '70-acm',
                                wait: true, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('EKS'){
                    steps {
                        script {
                            build job: '90-eks',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
            }
        }
        stage('ALB'){
            steps {
                script {
                    build job: '80-frontend-alb',
                        wait: false, // Wait for completion
                        propagate: false // Propagate status
                }
            }
        }

    }
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}